//! Artifact-level regression guard for the Zisk
//! `gsum_debug_data_global` body payload distribution.
//!
//! Pins the combined Round 2 / Round 4 producer fixes:
//! the 74 body entries must all have `opids` of length 64 and
//! `num_reps` operand-class distribution `{proofvalue: 8,
//! number: 66}` matching the golden JS producer. The checked-in
//! `pil/zisk.pilout` is regenerated by the workspace's pil2c on
//! every HEAD change, so this test spawns `pil2c` freshly on
//! the full Zisk source tree and decodes the resulting pilout.
//!
//! The test is gated on an env var (`ZISK_PARITY_TEST=1`) by
//! default so `cargo test` on a contributor machine stays
//! quick; CI and the RLCR loop explicitly opt in by setting
//! the flag. On opt-in, the test takes ~3-4 minutes.

use std::path::PathBuf;
use std::process::Command;

use pil2_compiler_rust::proto_out::pilout_proto as pb;
use prost::Message;

#[test]
fn zisk_gsum_debug_data_global_matches_golden_distribution() {
    if std::env::var_os("ZISK_PARITY_TEST").is_none() {
        eprintln!(
            "skipping zisk_gsum_debug_data_global_matches_golden_distribution; \
             set ZISK_PARITY_TEST=1 to run the full Zisk pil2c regeneration"
        );
        return;
    }

    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace = manifest.parent().expect("manifest parent");

    let zisk_pil = workspace.join("pil").join("zisk.pil");
    assert!(
        zisk_pil.is_file(),
        "zisk.pil not found at {}",
        zisk_pil.display()
    );

    let include_paths = vec![
        workspace.join("pil"),
        workspace
            .join("pil2-proofman")
            .join("pil2-components")
            .join("lib")
            .join("std")
            .join("pil"),
        workspace.join("state-machines"),
        workspace.join("precompiles"),
    ];
    let include_arg = include_paths
        .iter()
        .map(|p| p.to_string_lossy().to_string())
        .collect::<Vec<_>>()
        .join(",");

    let bin = PathBuf::from(env!("CARGO_BIN_EXE_pil2c"));
    let out = std::env::temp_dir().join("pil2c_zisk_parity_test.pilout");
    let fx_dir = std::env::temp_dir().join("pil2c_zisk_parity_fx");
    let _ = std::fs::remove_file(&out);
    let _ = std::fs::create_dir_all(&fx_dir);

    let _output = Command::new(&bin)
        .arg(&zisk_pil)
        .arg("-I")
        .arg(&include_arg)
        .arg("-o")
        .arg(&out)
        .arg("-u")
        .arg(&fx_dir)
        .arg("-O")
        .arg("fixed-to-file")
        .output()
        .expect("failed to spawn pil2c");
    // pil2c may return non-zero for unrelated residual runtime
    // errors in other AIRs (stdlib voids that post-date this
    // regression's target). The pilout file is still written in
    // that case and its artifact-level shape is what this test
    // guards. Require the pilout file exists and the global
    // constraints decode cleanly; the exit code is advisory.
    assert!(
        out.is_file(),
        "pil2c did not produce {} (stdout {} bytes, stderr {} bytes)",
        out.display(),
        _output.stdout.len(),
        _output.stderr.len()
    );

    let bytes = std::fs::read(&out).expect("read zisk.pilout");
    let pilout = pb::PilOut::decode(bytes.as_slice()).expect("decode zisk.pilout");

    // Proto-scope hints only (air_group_id and air_id both None).
    let global_hints: Vec<&pb::Hint> = pilout
        .hints
        .iter()
        .filter(|h| {
            h.name == "gsum_debug_data_global"
                && h.air_group_id.is_none()
                && h.air_id.is_none()
        })
        .collect();

    // One header entry + 74 body entries.
    assert_eq!(
        global_hints.len(),
        75,
        "expected 75 proof-scope gsum_debug_data_global entries (1 header + 74 body); \
         got {}",
        global_hints.len()
    );

    // Walk the body entries (skip header at index 0).
    let body = &global_hints[1..];
    assert_eq!(body.len(), 74, "expected 74 body entries");

    // Helper: find a named sub-field in an entry's first HintFieldArray.
    fn named_field<'a>(h: &'a pb::Hint, name: &str) -> &'a pb::HintField {
        let top = h
            .hint_fields
            .first()
            .unwrap_or_else(|| panic!("gsum_debug_data_global entry had no hint_fields"));
        let arr = match top.value.as_ref() {
            Some(pb::hint_field::Value::HintFieldArray(a)) => a,
            other => panic!("top field must wrap HintFieldArray, got {:?}", other),
        };
        arr.hint_fields
            .iter()
            .find(|f| f.name.as_deref() == Some(name))
            .unwrap_or_else(|| {
                panic!("gsum_debug_data_global entry missing {:?} sub-field", name)
            })
    }

    // opids length histogram: must be {64: 74}.
    let mut opids_len_counts: std::collections::BTreeMap<usize, usize> =
        std::collections::BTreeMap::new();
    for h in body {
        let opids = named_field(h, "opids");
        let arr = match opids.value.as_ref() {
            Some(pb::hint_field::Value::HintFieldArray(a)) => a,
            other => panic!("opids must be HintFieldArray; got {:?}", other),
        };
        *opids_len_counts.entry(arr.hint_fields.len()).or_insert(0) += 1;
    }
    assert_eq!(
        opids_len_counts,
        [(64usize, 74usize)].into_iter().collect(),
        "opids length distribution mismatches golden (expected {{64: 74}}); \
         got {:?}. The Round 2 get_direct_ref + Round 4 Scope::declare fixes \
         must be preserved to keep this golden.",
        opids_len_counts
    );

    // num_reps op histogram: must be {proofvalue: 8, number: 66}.
    let mut num_reps_op_counts: std::collections::BTreeMap<&'static str, usize> =
        std::collections::BTreeMap::new();
    for h in body {
        let nr = named_field(h, "num_reps");
        let op = match nr.value.as_ref() {
            Some(pb::hint_field::Value::Operand(op_wrap)) => {
                op_wrap.operand.as_ref().unwrap_or_else(|| {
                    panic!("num_reps Operand had no inner")
                })
            }
            other => panic!("num_reps must wrap Operand; got {:?}", other),
        };
        let key: &'static str = match op {
            pb::operand::Operand::ProofValue(_) => "proofvalue",
            pb::operand::Operand::Constant(_) => "number",
            pb::operand::Operand::WitnessCol(_) => "witnesscol",
            pb::operand::Operand::AirValue(_) => "airvalue",
            pb::operand::Operand::AirGroupValue(_) => "airgroupvalue",
            pb::operand::Operand::Challenge(_) => "challenge",
            pb::operand::Operand::Expression(_) => "expression",
            _ => "other",
        };
        *num_reps_op_counts.entry(key).or_insert(0) += 1;
    }
    let expected: std::collections::BTreeMap<&'static str, usize> =
        [("proofvalue", 8usize), ("number", 66usize)].into_iter().collect();
    assert_eq!(
        num_reps_op_counts, expected,
        "num_reps op distribution mismatches golden (expected {{proofvalue: 8, number: 66}}); \
         got {:?}. The Round 4 Scope::declare same-depth preservation fix must be \
         preserved to keep this golden.",
        num_reps_op_counts
    );

    let _ = std::fs::remove_file(&out);
}
